/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "output.h"

#include <stdint.h>
#include "startup.h"
#include "serial.h"
#include "timer.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint8_t string_to_send[64] = "and the rest!\r\n";

// idea 1 have a function here that calls serial output
// assume that global string will be put in
void transmission_triggered(){
	setup_transmission(string_to_send, &USART1_PORT);
}


int main(void)
{
	// Enable Clocks
	enable_clocks();

	// Set up LED module
	initialise_board();

	// Set up USART board rate
	SerialInitialise(BAUD_115200, &USART1_PORT, transmission_triggered);

	// Set up timer module in interval mode
	// here 200 = approx 2seconds cool
	uint32_t time_mili = 2000;


	// Pass transmission triggered to function pointer
	up_count_TIM3(time_mili, transmission_triggered);


    /* Loop forever */
	for(;;);
}
