/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// enable the clocks for desired peripherals (GPIOA, C and E)
void enable_clocks() {
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;
}

void initialise_led() {
    uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
    *led_output_registers = 0x5555;
}

void toggle_led() {
	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

	int random_num = rand() % 4; // generate random number between 0 and 3
	    switch (random_num) {
	        case 0:
	            *led_register = 0b00000010; // set bit for LED 1
	            break;
	        case 1:
	            *led_register = 0b00001000; // set bit for LED 2
	            break;
	        case 2:
	            *led_register = 0b00100000; // set bit for LED 3
	            break;
	        case 3:
	            *led_register = 0b10000000; // set bit for LED 4
	            break;
	        default:
	            break;
	    }
}


int main(void) {
    enable_clocks();
    initialise_led();
    toggle_led();

}
